server:
  port: 8080
  servlet:
    contextPath: /security
management:
  port: 8081
  health:
    mail:
      enabled: false
spring:
  datasource:
    name: primaryDataSource
    username: root
    password: lotus
    url: jdbc:mysql://127.0.0.1:3306/ncee?sessionVariables=foreign_key_checks=0&serverTimezone=CTT&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    #close foreign key checking for unit test    
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:mybatis.cfg.xml